// <auto-generated />
namespace HrsVerification.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _1migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201311131558213_1migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
